server:
  port: 80

spring:
  datasource:
    platform: postgresql
    url: jdbc:postgresql://localhost:5432/MusteriDB
    username: postgres
    password: 20008132460sY
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update